import { INodeProperties } from 'n8n-workflow';

export const setSettingsFields: INodeProperties[] = [
	{
		displayName: 'Settings',
		name: 'settings',
		type: 'collection',
		default: {},
		options: [
			{
				displayName: 'delaySendMessagesMilliseconds',
				name: 'delaySendMessagesMilliseconds',
				type: 'number',
				placeholder: 'Recommended 15000',
				default: 15000,
				description: 'Message sending delay in milliseconds. Recommended value: 15000.',
			},
			{
				displayName: 'deletedMessageWebhook',
				name: 'deletedMessageWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about deleted messages',
			},
			{
				displayName: 'editedMessageWebhook',
				name: 'editedMessageWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about edited messages',
			},
			{
				displayName: 'incomingCallWebhook',
				name: 'incomingCallWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about incoming calls',
			},
			{
				displayName: 'incomingWebhook',
				name: 'incomingWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about incoming messages and files',
			},
			{
				displayName: 'keepOnlineStatus',
				name: 'keepOnlineStatus',
				type: 'boolean',
				default: false,
				description: 'Whether to keep "online" status',
			},
			{
				displayName: 'markIncomingMessagesReaded',
				name: 'markIncomingMessagesReaded',
				type: 'boolean',
				default: false,
				description: 'Whether to mark incoming messages as read on reply from API',
			},
			{
				displayName: 'outgoingAPIMessageWebhook',
				name: 'outgoingAPIMessageWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about messages sent from API',
			},
			{
				displayName: 'outgoingMessageWebhook',
				name: 'outgoingMessageWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about messages sent from the phone',
			},
			{
				displayName: 'outgoingWebhook',
				name: 'outgoingWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about outgoing messages statuses',
			},
			{
				displayName: 'pollMessageWebhook',
				name: 'pollMessageWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about polls',
			},
			{
				displayName: 'stateWebhook',
				name: 'stateWebhook',
				type: 'boolean',
				default: false,
				description: 'Whether to receive notifications about the instance authorization state change',
			},
			{
				displayName: 'webhookUrl',
				name: 'webhookUrl',
				type: 'string',
				default: '',
				description: 'URL for sending notifications',
			},
			{
				displayName: 'webhookUrlToken',
				name: 'webhookUrlToken',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'Token to access your notification server',
			},
		],
		displayOptions: {
			show: {
				resource: ['account'],
				operation: ['setSettings'],
			},
		},
		required: true,
	},
];